# Generated by Django 3.2.6 on 2022-02-16 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('designation', models.CharField(max_length=50)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_data.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='UserImportFile',
        ),
    ]
