# Generated by Django 3.2.6 on 2022-02-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0006_auto_20220217_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_data',
            name='imported_by',
            field=models.CharField(max_length=100),
        ),
    ]
